### ISSUE TITLE
runapp-docker.bat has wrong image name in it

### ISSUE THREAD

**Issue by awoodobvio** [sonatype-nexus-community/nexusiq-successmetrics#101]
ghcr.io/sonatype-nexus-community/getmetrics:98
vs
ghcr.io/sonatype-nexus-community/nexusiq-successmetrics-get-metrics:98

**Comment by rpanman-sonatype** [comment]
Thanks for pointing that out. I've corrected it and included it in release 99. If you could confirm it works for you now, that would be great. Thanks!

**Comment by awoodobvio** [comment]
This has been fixed, but still unable to run the latest code.  Creating a new issue for the error I'm receiving.
