### ISSUE TITLE
IQ n-level hierarchy considerations in Success Metrics Script

### ISSUE THREAD

**Issue by caw916** [sonatype-nexus-community/nexusiq-successmetrics#110]
The IQ n-level hierarchy capability is expected to be implemented soon.  The Success Metrics Script should align with this capability.

**Comment by rpanman-sonatype** [comment]
Hiya, when I checked with the product team they indicated that there shouldn't be any impact from N-level hierarchy, however I'll leave this issue open until it is formally released and we can confirm.

**Comment by rpanman-sonatype** [comment]
Sonatype IQ release 156 comes with N-level hierarchy (:tada:) and so I tested how this effected the output of the successmetrics API. The result is that are no new fields in the successmetrics API output, and the organisation assigned to the application is its parent organisation (not it’s grandparent etc). As an example the “Advent of Code 2022” application in the image below is listed by successmetrics as being in the “Test_child_org” organisation.
![image](https://user-images.githubusercontent.com/95854467/222678339-2479d662-40a1-42df-9b42-21cd46c8b28a.png)
