### ISSUE TITLE
Future Extension of Metrics Tool

### ISSUE THREAD

**Issue by colinoconghaile** [sonatype-nexus-community/nexusiq-successmetrics#99]
I'm just wondering is there any plans to extend the metrics tool? When I currently run the metrics tool (version 98), the CSV file that is created only shows a certain amount of data. Are there any plans to add to that? 

I'm interested in the open security violations. Is there a way to show the unique open security violations? The CSV file might show say 25 critical violations but when you open a build report for the same application, the critical violation will be say 25 but when AGGREGATED BY COMPONENT is ticked, it'll only show like 10 critical errors because a component might have multiple. Is there a way to get the UNIQUE open security critical violations?

**Comment by rpanman-sonatype** [comment]
Hey there, sorry for the long delay, email notifications were switched off for some reason so I missed this.

The data in that successmetrics.csv comes directly from the [Sonatype Success Metrics API](https://help.sonatype.com/iqserver/automating/rest-apis/success-metrics-data-rest-api---v2), I've not heard any plans from Sonatype on changing that output.

It's possible to get a view of the data from the [Report-related REST API](https://help.sonatype.com/iqserver/automating/rest-apis/report-related-rest-apis---v2) a GET call like this:
`{{iq_host}}/api/v2/applications/{{application_id}}/reports/{{report_id}/raw`
... that wouldn't scale very well for this tool though, and you'd need to cycle through the latest reports for all stages to get a consolidated view.

**Comment by colinoconghaile** [comment]
No worries on the delay. I have also contacted Sonatype on this but no joy yet. I may be waiting a while :) The Report-related REST API is just not feasible for me currently as I have to many applications. It would take me a day, if not more to get through them all
